/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppCoreRouteRouteImport } from './routes/_app/_core/route'
import { Route as AppAuthRouteRouteImport } from './routes/_app/_auth/route'
import { Route as AppCoreReportsRouteImport } from './routes/_app/_core/reports'
import { Route as AppCoreDashboardRouteImport } from './routes/_app/_core/dashboard'
import { Route as AppCoreAssistantRouteImport } from './routes/_app/_core/assistant'
import { Route as AppCoreAnalyzeRouteImport } from './routes/_app/_core/analyze'
import { Route as AppAuthResetPasswordRouteImport } from './routes/_app/_auth/reset-password'
import { Route as AppAuthRegisterRouteImport } from './routes/_app/_auth/register'
import { Route as AppAuthLoginRouteImport } from './routes/_app/_auth/login'
import { Route as AppAuthForgotPasswordRouteImport } from './routes/_app/_auth/forgot-password'
import { Route as AppCoreUsersRouteRouteImport } from './routes/_app/_core/users/route'
import { Route as AppCoreMembersRouteRouteImport } from './routes/_app/_core/members/route'
import { Route as AppCoreBranchesRouteRouteImport } from './routes/_app/_core/branches/route'
import { Route as AppCoreUsersIndexRouteImport } from './routes/_app/_core/users/index'
import { Route as AppCoreOrganizationIndexRouteImport } from './routes/_app/_core/organization/index'
import { Route as AppCoreMembersIndexRouteImport } from './routes/_app/_core/members/index'
import { Route as AppCoreBranchesIndexRouteImport } from './routes/_app/_core/branches/index'
import { Route as AppCoreUsersCreateRouteImport } from './routes/_app/_core/users/create'
import { Route as AppCoreOrganizationProfileRouteImport } from './routes/_app/_core/organization/profile'
import { Route as AppCoreOrganizationCreateRouteImport } from './routes/_app/_core/organization/create'
import { Route as AppCoreMembersCreateRouteImport } from './routes/_app/_core/members/create'
import { Route as AppCoreCheckInsScannerRouteImport } from './routes/_app/_core/check-ins/scanner'
import { Route as AppCoreBranchesCreateRouteImport } from './routes/_app/_core/branches/create'
import { Route as AppCoreBillingSubscriptionsRouteRouteImport } from './routes/_app/_core/billing/subscriptions/route'
import { Route as AppCoreBillingPlansRouteRouteImport } from './routes/_app/_core/billing/plans/route'
import { Route as AppCoreUsersTeamIndexRouteImport } from './routes/_app/_core/users/team/index'
import { Route as AppCoreOrganizationModulesIndexRouteImport } from './routes/_app/_core/organization/modules/index'
import { Route as AppCoreBillingSubscriptionsIndexRouteImport } from './routes/_app/_core/billing/subscriptions/index'
import { Route as AppCoreBillingPlansIndexRouteImport } from './routes/_app/_core/billing/plans/index'
import { Route as AppCoreUsersTeamCreateRouteImport } from './routes/_app/_core/users/team/create'
import { Route as AppCoreUsersIdUpdateRouteImport } from './routes/_app/_core/users/$id.update'
import { Route as AppCoreOrganizationModulesCreateRouteImport } from './routes/_app/_core/organization/modules/create'
import { Route as AppCoreOrganizationIdUpdateRouteImport } from './routes/_app/_core/organization/$id.update'
import { Route as AppCoreMembersIdUpdateRouteImport } from './routes/_app/_core/members/$id/update'
import { Route as AppCoreBranchesIdUpdateRouteImport } from './routes/_app/_core/branches/$id.update'
import { Route as AppCoreBillingPlansCreateRouteImport } from './routes/_app/_core/billing/plans/create'
import { Route as AppCoreUsersTeamIdUpdateRouteImport } from './routes/_app/_core/users/team/$id.update'
import { Route as AppCoreOrganizationModulesIdUpdateRouteImport } from './routes/_app/_core/organization/modules/$id.update'
import { Route as AppCoreBillingPlansPlanIdUpdateRouteImport } from './routes/_app/_core/billing/plans/$planId/update'

const AppRouteLazyRouteImport = createFileRoute('/_app')()

const AppRouteLazyRoute = AppRouteLazyRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_app/route.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoreRouteRoute = AppCoreRouteRouteImport.update({
  id: '/_core',
  getParentRoute: () => AppRouteLazyRoute,
} as any)
const AppAuthRouteRoute = AppAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRouteLazyRoute,
} as any)
const AppCoreReportsRoute = AppCoreReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppCoreRouteRoute,
} as any)
const AppCoreDashboardRoute = AppCoreDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppCoreRouteRoute,
} as any)
const AppCoreAssistantRoute = AppCoreAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppCoreRouteRoute,
} as any)
const AppCoreAnalyzeRoute = AppCoreAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppCoreRouteRoute,
} as any)
const AppAuthResetPasswordRoute = AppAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthRegisterRoute = AppAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthLoginRoute = AppAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthForgotPasswordRoute = AppAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppCoreUsersRouteRoute = AppCoreUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppCoreRouteRoute,
} as any)
const AppCoreMembersRouteRoute = AppCoreMembersRouteRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppCoreRouteRoute,
} as any)
const AppCoreBranchesRouteRoute = AppCoreBranchesRouteRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppCoreRouteRoute,
} as any)
const AppCoreUsersIndexRoute = AppCoreUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoreUsersRouteRoute,
} as any)
const AppCoreOrganizationIndexRoute =
  AppCoreOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AppCoreRouteRoute,
  } as any)
const AppCoreMembersIndexRoute = AppCoreMembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoreMembersRouteRoute,
} as any)
const AppCoreBranchesIndexRoute = AppCoreBranchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoreBranchesRouteRoute,
} as any)
const AppCoreUsersCreateRoute = AppCoreUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppCoreUsersRouteRoute,
} as any)
const AppCoreOrganizationProfileRoute =
  AppCoreOrganizationProfileRouteImport.update({
    id: '/organization/profile',
    path: '/organization/profile',
    getParentRoute: () => AppCoreRouteRoute,
  } as any)
const AppCoreOrganizationCreateRoute =
  AppCoreOrganizationCreateRouteImport.update({
    id: '/organization/create',
    path: '/organization/create',
    getParentRoute: () => AppCoreRouteRoute,
  } as any)
const AppCoreMembersCreateRoute = AppCoreMembersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppCoreMembersRouteRoute,
} as any)
const AppCoreCheckInsScannerRoute = AppCoreCheckInsScannerRouteImport.update({
  id: '/check-ins/scanner',
  path: '/check-ins/scanner',
  getParentRoute: () => AppCoreRouteRoute,
} as any)
const AppCoreBranchesCreateRoute = AppCoreBranchesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppCoreBranchesRouteRoute,
} as any)
const AppCoreBillingSubscriptionsRouteRoute =
  AppCoreBillingSubscriptionsRouteRouteImport.update({
    id: '/billing/subscriptions',
    path: '/billing/subscriptions',
    getParentRoute: () => AppCoreRouteRoute,
  } as any)
const AppCoreBillingPlansRouteRoute =
  AppCoreBillingPlansRouteRouteImport.update({
    id: '/billing/plans',
    path: '/billing/plans',
    getParentRoute: () => AppCoreRouteRoute,
  } as any)
const AppCoreUsersTeamIndexRoute = AppCoreUsersTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppCoreUsersRouteRoute,
} as any)
const AppCoreOrganizationModulesIndexRoute =
  AppCoreOrganizationModulesIndexRouteImport.update({
    id: '/organization/modules/',
    path: '/organization/modules/',
    getParentRoute: () => AppCoreRouteRoute,
  } as any)
const AppCoreBillingSubscriptionsIndexRoute =
  AppCoreBillingSubscriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCoreBillingSubscriptionsRouteRoute,
  } as any)
const AppCoreBillingPlansIndexRoute =
  AppCoreBillingPlansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCoreBillingPlansRouteRoute,
  } as any)
const AppCoreUsersTeamCreateRoute = AppCoreUsersTeamCreateRouteImport.update({
  id: '/team/create',
  path: '/team/create',
  getParentRoute: () => AppCoreUsersRouteRoute,
} as any)
const AppCoreUsersIdUpdateRoute = AppCoreUsersIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => AppCoreUsersRouteRoute,
} as any)
const AppCoreOrganizationModulesCreateRoute =
  AppCoreOrganizationModulesCreateRouteImport.update({
    id: '/organization/modules/create',
    path: '/organization/modules/create',
    getParentRoute: () => AppCoreRouteRoute,
  } as any)
const AppCoreOrganizationIdUpdateRoute =
  AppCoreOrganizationIdUpdateRouteImport.update({
    id: '/organization/$id/update',
    path: '/organization/$id/update',
    getParentRoute: () => AppCoreRouteRoute,
  } as any)
const AppCoreMembersIdUpdateRoute = AppCoreMembersIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => AppCoreMembersRouteRoute,
} as any)
const AppCoreBranchesIdUpdateRoute = AppCoreBranchesIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => AppCoreBranchesRouteRoute,
} as any)
const AppCoreBillingPlansCreateRoute =
  AppCoreBillingPlansCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppCoreBillingPlansRouteRoute,
  } as any)
const AppCoreUsersTeamIdUpdateRoute =
  AppCoreUsersTeamIdUpdateRouteImport.update({
    id: '/team/$id/update',
    path: '/team/$id/update',
    getParentRoute: () => AppCoreUsersRouteRoute,
  } as any)
const AppCoreOrganizationModulesIdUpdateRoute =
  AppCoreOrganizationModulesIdUpdateRouteImport.update({
    id: '/organization/modules/$id/update',
    path: '/organization/modules/$id/update',
    getParentRoute: () => AppCoreRouteRoute,
  } as any)
const AppCoreBillingPlansPlanIdUpdateRoute =
  AppCoreBillingPlansPlanIdUpdateRouteImport.update({
    id: '/$planId/update',
    path: '/$planId/update',
    getParentRoute: () => AppCoreBillingPlansRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof AppCoreBranchesRouteRouteWithChildren
  '/members': typeof AppCoreMembersRouteRouteWithChildren
  '/users': typeof AppCoreUsersRouteRouteWithChildren
  '/forgot-password': typeof AppAuthForgotPasswordRoute
  '/login': typeof AppAuthLoginRoute
  '/register': typeof AppAuthRegisterRoute
  '/reset-password': typeof AppAuthResetPasswordRoute
  '/analyze': typeof AppCoreAnalyzeRoute
  '/assistant': typeof AppCoreAssistantRoute
  '/dashboard': typeof AppCoreDashboardRoute
  '/reports': typeof AppCoreReportsRoute
  '/billing/plans': typeof AppCoreBillingPlansRouteRouteWithChildren
  '/billing/subscriptions': typeof AppCoreBillingSubscriptionsRouteRouteWithChildren
  '/branches/create': typeof AppCoreBranchesCreateRoute
  '/check-ins/scanner': typeof AppCoreCheckInsScannerRoute
  '/members/create': typeof AppCoreMembersCreateRoute
  '/organization/create': typeof AppCoreOrganizationCreateRoute
  '/organization/profile': typeof AppCoreOrganizationProfileRoute
  '/users/create': typeof AppCoreUsersCreateRoute
  '/branches/': typeof AppCoreBranchesIndexRoute
  '/members/': typeof AppCoreMembersIndexRoute
  '/organization': typeof AppCoreOrganizationIndexRoute
  '/users/': typeof AppCoreUsersIndexRoute
  '/billing/plans/create': typeof AppCoreBillingPlansCreateRoute
  '/branches/$id/update': typeof AppCoreBranchesIdUpdateRoute
  '/members/$id/update': typeof AppCoreMembersIdUpdateRoute
  '/organization/$id/update': typeof AppCoreOrganizationIdUpdateRoute
  '/organization/modules/create': typeof AppCoreOrganizationModulesCreateRoute
  '/users/$id/update': typeof AppCoreUsersIdUpdateRoute
  '/users/team/create': typeof AppCoreUsersTeamCreateRoute
  '/billing/plans/': typeof AppCoreBillingPlansIndexRoute
  '/billing/subscriptions/': typeof AppCoreBillingSubscriptionsIndexRoute
  '/organization/modules': typeof AppCoreOrganizationModulesIndexRoute
  '/users/team': typeof AppCoreUsersTeamIndexRoute
  '/billing/plans/$planId/update': typeof AppCoreBillingPlansPlanIdUpdateRoute
  '/organization/modules/$id/update': typeof AppCoreOrganizationModulesIdUpdateRoute
  '/users/team/$id/update': typeof AppCoreUsersTeamIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AppAuthForgotPasswordRoute
  '/login': typeof AppAuthLoginRoute
  '/register': typeof AppAuthRegisterRoute
  '/reset-password': typeof AppAuthResetPasswordRoute
  '/analyze': typeof AppCoreAnalyzeRoute
  '/assistant': typeof AppCoreAssistantRoute
  '/dashboard': typeof AppCoreDashboardRoute
  '/reports': typeof AppCoreReportsRoute
  '/branches/create': typeof AppCoreBranchesCreateRoute
  '/check-ins/scanner': typeof AppCoreCheckInsScannerRoute
  '/members/create': typeof AppCoreMembersCreateRoute
  '/organization/create': typeof AppCoreOrganizationCreateRoute
  '/organization/profile': typeof AppCoreOrganizationProfileRoute
  '/users/create': typeof AppCoreUsersCreateRoute
  '/branches': typeof AppCoreBranchesIndexRoute
  '/members': typeof AppCoreMembersIndexRoute
  '/organization': typeof AppCoreOrganizationIndexRoute
  '/users': typeof AppCoreUsersIndexRoute
  '/billing/plans/create': typeof AppCoreBillingPlansCreateRoute
  '/branches/$id/update': typeof AppCoreBranchesIdUpdateRoute
  '/members/$id/update': typeof AppCoreMembersIdUpdateRoute
  '/organization/$id/update': typeof AppCoreOrganizationIdUpdateRoute
  '/organization/modules/create': typeof AppCoreOrganizationModulesCreateRoute
  '/users/$id/update': typeof AppCoreUsersIdUpdateRoute
  '/users/team/create': typeof AppCoreUsersTeamCreateRoute
  '/billing/plans': typeof AppCoreBillingPlansIndexRoute
  '/billing/subscriptions': typeof AppCoreBillingSubscriptionsIndexRoute
  '/organization/modules': typeof AppCoreOrganizationModulesIndexRoute
  '/users/team': typeof AppCoreUsersTeamIndexRoute
  '/billing/plans/$planId/update': typeof AppCoreBillingPlansPlanIdUpdateRoute
  '/organization/modules/$id/update': typeof AppCoreOrganizationModulesIdUpdateRoute
  '/users/team/$id/update': typeof AppCoreUsersTeamIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteLazyRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteRouteWithChildren
  '/_app/_core': typeof AppCoreRouteRouteWithChildren
  '/_app/_core/branches': typeof AppCoreBranchesRouteRouteWithChildren
  '/_app/_core/members': typeof AppCoreMembersRouteRouteWithChildren
  '/_app/_core/users': typeof AppCoreUsersRouteRouteWithChildren
  '/_app/_auth/forgot-password': typeof AppAuthForgotPasswordRoute
  '/_app/_auth/login': typeof AppAuthLoginRoute
  '/_app/_auth/register': typeof AppAuthRegisterRoute
  '/_app/_auth/reset-password': typeof AppAuthResetPasswordRoute
  '/_app/_core/analyze': typeof AppCoreAnalyzeRoute
  '/_app/_core/assistant': typeof AppCoreAssistantRoute
  '/_app/_core/dashboard': typeof AppCoreDashboardRoute
  '/_app/_core/reports': typeof AppCoreReportsRoute
  '/_app/_core/billing/plans': typeof AppCoreBillingPlansRouteRouteWithChildren
  '/_app/_core/billing/subscriptions': typeof AppCoreBillingSubscriptionsRouteRouteWithChildren
  '/_app/_core/branches/create': typeof AppCoreBranchesCreateRoute
  '/_app/_core/check-ins/scanner': typeof AppCoreCheckInsScannerRoute
  '/_app/_core/members/create': typeof AppCoreMembersCreateRoute
  '/_app/_core/organization/create': typeof AppCoreOrganizationCreateRoute
  '/_app/_core/organization/profile': typeof AppCoreOrganizationProfileRoute
  '/_app/_core/users/create': typeof AppCoreUsersCreateRoute
  '/_app/_core/branches/': typeof AppCoreBranchesIndexRoute
  '/_app/_core/members/': typeof AppCoreMembersIndexRoute
  '/_app/_core/organization/': typeof AppCoreOrganizationIndexRoute
  '/_app/_core/users/': typeof AppCoreUsersIndexRoute
  '/_app/_core/billing/plans/create': typeof AppCoreBillingPlansCreateRoute
  '/_app/_core/branches/$id/update': typeof AppCoreBranchesIdUpdateRoute
  '/_app/_core/members/$id/update': typeof AppCoreMembersIdUpdateRoute
  '/_app/_core/organization/$id/update': typeof AppCoreOrganizationIdUpdateRoute
  '/_app/_core/organization/modules/create': typeof AppCoreOrganizationModulesCreateRoute
  '/_app/_core/users/$id/update': typeof AppCoreUsersIdUpdateRoute
  '/_app/_core/users/team/create': typeof AppCoreUsersTeamCreateRoute
  '/_app/_core/billing/plans/': typeof AppCoreBillingPlansIndexRoute
  '/_app/_core/billing/subscriptions/': typeof AppCoreBillingSubscriptionsIndexRoute
  '/_app/_core/organization/modules/': typeof AppCoreOrganizationModulesIndexRoute
  '/_app/_core/users/team/': typeof AppCoreUsersTeamIndexRoute
  '/_app/_core/billing/plans/$planId/update': typeof AppCoreBillingPlansPlanIdUpdateRoute
  '/_app/_core/organization/modules/$id/update': typeof AppCoreOrganizationModulesIdUpdateRoute
  '/_app/_core/users/team/$id/update': typeof AppCoreUsersTeamIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/members'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/analyze'
    | '/assistant'
    | '/dashboard'
    | '/reports'
    | '/billing/plans'
    | '/billing/subscriptions'
    | '/branches/create'
    | '/check-ins/scanner'
    | '/members/create'
    | '/organization/create'
    | '/organization/profile'
    | '/users/create'
    | '/branches/'
    | '/members/'
    | '/organization'
    | '/users/'
    | '/billing/plans/create'
    | '/branches/$id/update'
    | '/members/$id/update'
    | '/organization/$id/update'
    | '/organization/modules/create'
    | '/users/$id/update'
    | '/users/team/create'
    | '/billing/plans/'
    | '/billing/subscriptions/'
    | '/organization/modules'
    | '/users/team'
    | '/billing/plans/$planId/update'
    | '/organization/modules/$id/update'
    | '/users/team/$id/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/analyze'
    | '/assistant'
    | '/dashboard'
    | '/reports'
    | '/branches/create'
    | '/check-ins/scanner'
    | '/members/create'
    | '/organization/create'
    | '/organization/profile'
    | '/users/create'
    | '/branches'
    | '/members'
    | '/organization'
    | '/users'
    | '/billing/plans/create'
    | '/branches/$id/update'
    | '/members/$id/update'
    | '/organization/$id/update'
    | '/organization/modules/create'
    | '/users/$id/update'
    | '/users/team/create'
    | '/billing/plans'
    | '/billing/subscriptions'
    | '/organization/modules'
    | '/users/team'
    | '/billing/plans/$planId/update'
    | '/organization/modules/$id/update'
    | '/users/team/$id/update'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/_app/_core'
    | '/_app/_core/branches'
    | '/_app/_core/members'
    | '/_app/_core/users'
    | '/_app/_auth/forgot-password'
    | '/_app/_auth/login'
    | '/_app/_auth/register'
    | '/_app/_auth/reset-password'
    | '/_app/_core/analyze'
    | '/_app/_core/assistant'
    | '/_app/_core/dashboard'
    | '/_app/_core/reports'
    | '/_app/_core/billing/plans'
    | '/_app/_core/billing/subscriptions'
    | '/_app/_core/branches/create'
    | '/_app/_core/check-ins/scanner'
    | '/_app/_core/members/create'
    | '/_app/_core/organization/create'
    | '/_app/_core/organization/profile'
    | '/_app/_core/users/create'
    | '/_app/_core/branches/'
    | '/_app/_core/members/'
    | '/_app/_core/organization/'
    | '/_app/_core/users/'
    | '/_app/_core/billing/plans/create'
    | '/_app/_core/branches/$id/update'
    | '/_app/_core/members/$id/update'
    | '/_app/_core/organization/$id/update'
    | '/_app/_core/organization/modules/create'
    | '/_app/_core/users/$id/update'
    | '/_app/_core/users/team/create'
    | '/_app/_core/billing/plans/'
    | '/_app/_core/billing/subscriptions/'
    | '/_app/_core/organization/modules/'
    | '/_app/_core/users/team/'
    | '/_app/_core/billing/plans/$planId/update'
    | '/_app/_core/organization/modules/$id/update'
    | '/_app/_core/users/team/$id/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteLazyRoute: typeof AppRouteLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_core': {
      id: '/_app/_core'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppCoreRouteRouteImport
      parentRoute: typeof AppRouteLazyRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthRouteRouteImport
      parentRoute: typeof AppRouteLazyRoute
    }
    '/_app/_core/reports': {
      id: '/_app/_core/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppCoreReportsRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/dashboard': {
      id: '/_app/_core/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppCoreDashboardRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/assistant': {
      id: '/_app/_core/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppCoreAssistantRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/analyze': {
      id: '/_app/_core/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AppCoreAnalyzeRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_auth/reset-password': {
      id: '/_app/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AppAuthResetPasswordRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/register': {
      id: '/_app/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppAuthRegisterRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/login': {
      id: '/_app/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppAuthLoginRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/forgot-password': {
      id: '/_app/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppAuthForgotPasswordRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_core/users': {
      id: '/_app/_core/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppCoreUsersRouteRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/members': {
      id: '/_app/_core/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppCoreMembersRouteRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/branches': {
      id: '/_app/_core/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppCoreBranchesRouteRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/users/': {
      id: '/_app/_core/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AppCoreUsersIndexRouteImport
      parentRoute: typeof AppCoreUsersRouteRoute
    }
    '/_app/_core/organization/': {
      id: '/_app/_core/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppCoreOrganizationIndexRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/members/': {
      id: '/_app/_core/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof AppCoreMembersIndexRouteImport
      parentRoute: typeof AppCoreMembersRouteRoute
    }
    '/_app/_core/branches/': {
      id: '/_app/_core/branches/'
      path: '/'
      fullPath: '/branches/'
      preLoaderRoute: typeof AppCoreBranchesIndexRouteImport
      parentRoute: typeof AppCoreBranchesRouteRoute
    }
    '/_app/_core/users/create': {
      id: '/_app/_core/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AppCoreUsersCreateRouteImport
      parentRoute: typeof AppCoreUsersRouteRoute
    }
    '/_app/_core/organization/profile': {
      id: '/_app/_core/organization/profile'
      path: '/organization/profile'
      fullPath: '/organization/profile'
      preLoaderRoute: typeof AppCoreOrganizationProfileRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/organization/create': {
      id: '/_app/_core/organization/create'
      path: '/organization/create'
      fullPath: '/organization/create'
      preLoaderRoute: typeof AppCoreOrganizationCreateRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/members/create': {
      id: '/_app/_core/members/create'
      path: '/create'
      fullPath: '/members/create'
      preLoaderRoute: typeof AppCoreMembersCreateRouteImport
      parentRoute: typeof AppCoreMembersRouteRoute
    }
    '/_app/_core/check-ins/scanner': {
      id: '/_app/_core/check-ins/scanner'
      path: '/check-ins/scanner'
      fullPath: '/check-ins/scanner'
      preLoaderRoute: typeof AppCoreCheckInsScannerRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/branches/create': {
      id: '/_app/_core/branches/create'
      path: '/create'
      fullPath: '/branches/create'
      preLoaderRoute: typeof AppCoreBranchesCreateRouteImport
      parentRoute: typeof AppCoreBranchesRouteRoute
    }
    '/_app/_core/billing/subscriptions': {
      id: '/_app/_core/billing/subscriptions'
      path: '/billing/subscriptions'
      fullPath: '/billing/subscriptions'
      preLoaderRoute: typeof AppCoreBillingSubscriptionsRouteRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/billing/plans': {
      id: '/_app/_core/billing/plans'
      path: '/billing/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof AppCoreBillingPlansRouteRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/users/team/': {
      id: '/_app/_core/users/team/'
      path: '/team'
      fullPath: '/users/team'
      preLoaderRoute: typeof AppCoreUsersTeamIndexRouteImport
      parentRoute: typeof AppCoreUsersRouteRoute
    }
    '/_app/_core/organization/modules/': {
      id: '/_app/_core/organization/modules/'
      path: '/organization/modules'
      fullPath: '/organization/modules'
      preLoaderRoute: typeof AppCoreOrganizationModulesIndexRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/billing/subscriptions/': {
      id: '/_app/_core/billing/subscriptions/'
      path: '/'
      fullPath: '/billing/subscriptions/'
      preLoaderRoute: typeof AppCoreBillingSubscriptionsIndexRouteImport
      parentRoute: typeof AppCoreBillingSubscriptionsRouteRoute
    }
    '/_app/_core/billing/plans/': {
      id: '/_app/_core/billing/plans/'
      path: '/'
      fullPath: '/billing/plans/'
      preLoaderRoute: typeof AppCoreBillingPlansIndexRouteImport
      parentRoute: typeof AppCoreBillingPlansRouteRoute
    }
    '/_app/_core/users/team/create': {
      id: '/_app/_core/users/team/create'
      path: '/team/create'
      fullPath: '/users/team/create'
      preLoaderRoute: typeof AppCoreUsersTeamCreateRouteImport
      parentRoute: typeof AppCoreUsersRouteRoute
    }
    '/_app/_core/users/$id/update': {
      id: '/_app/_core/users/$id/update'
      path: '/$id/update'
      fullPath: '/users/$id/update'
      preLoaderRoute: typeof AppCoreUsersIdUpdateRouteImport
      parentRoute: typeof AppCoreUsersRouteRoute
    }
    '/_app/_core/organization/modules/create': {
      id: '/_app/_core/organization/modules/create'
      path: '/organization/modules/create'
      fullPath: '/organization/modules/create'
      preLoaderRoute: typeof AppCoreOrganizationModulesCreateRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/organization/$id/update': {
      id: '/_app/_core/organization/$id/update'
      path: '/organization/$id/update'
      fullPath: '/organization/$id/update'
      preLoaderRoute: typeof AppCoreOrganizationIdUpdateRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/members/$id/update': {
      id: '/_app/_core/members/$id/update'
      path: '/$id/update'
      fullPath: '/members/$id/update'
      preLoaderRoute: typeof AppCoreMembersIdUpdateRouteImport
      parentRoute: typeof AppCoreMembersRouteRoute
    }
    '/_app/_core/branches/$id/update': {
      id: '/_app/_core/branches/$id/update'
      path: '/$id/update'
      fullPath: '/branches/$id/update'
      preLoaderRoute: typeof AppCoreBranchesIdUpdateRouteImport
      parentRoute: typeof AppCoreBranchesRouteRoute
    }
    '/_app/_core/billing/plans/create': {
      id: '/_app/_core/billing/plans/create'
      path: '/create'
      fullPath: '/billing/plans/create'
      preLoaderRoute: typeof AppCoreBillingPlansCreateRouteImport
      parentRoute: typeof AppCoreBillingPlansRouteRoute
    }
    '/_app/_core/users/team/$id/update': {
      id: '/_app/_core/users/team/$id/update'
      path: '/team/$id/update'
      fullPath: '/users/team/$id/update'
      preLoaderRoute: typeof AppCoreUsersTeamIdUpdateRouteImport
      parentRoute: typeof AppCoreUsersRouteRoute
    }
    '/_app/_core/organization/modules/$id/update': {
      id: '/_app/_core/organization/modules/$id/update'
      path: '/organization/modules/$id/update'
      fullPath: '/organization/modules/$id/update'
      preLoaderRoute: typeof AppCoreOrganizationModulesIdUpdateRouteImport
      parentRoute: typeof AppCoreRouteRoute
    }
    '/_app/_core/billing/plans/$planId/update': {
      id: '/_app/_core/billing/plans/$planId/update'
      path: '/$planId/update'
      fullPath: '/billing/plans/$planId/update'
      preLoaderRoute: typeof AppCoreBillingPlansPlanIdUpdateRouteImport
      parentRoute: typeof AppCoreBillingPlansRouteRoute
    }
  }
}

interface AppAuthRouteRouteChildren {
  AppAuthForgotPasswordRoute: typeof AppAuthForgotPasswordRoute
  AppAuthLoginRoute: typeof AppAuthLoginRoute
  AppAuthRegisterRoute: typeof AppAuthRegisterRoute
  AppAuthResetPasswordRoute: typeof AppAuthResetPasswordRoute
}

const AppAuthRouteRouteChildren: AppAuthRouteRouteChildren = {
  AppAuthForgotPasswordRoute: AppAuthForgotPasswordRoute,
  AppAuthLoginRoute: AppAuthLoginRoute,
  AppAuthRegisterRoute: AppAuthRegisterRoute,
  AppAuthResetPasswordRoute: AppAuthResetPasswordRoute,
}

const AppAuthRouteRouteWithChildren = AppAuthRouteRoute._addFileChildren(
  AppAuthRouteRouteChildren,
)

interface AppCoreBranchesRouteRouteChildren {
  AppCoreBranchesCreateRoute: typeof AppCoreBranchesCreateRoute
  AppCoreBranchesIndexRoute: typeof AppCoreBranchesIndexRoute
  AppCoreBranchesIdUpdateRoute: typeof AppCoreBranchesIdUpdateRoute
}

const AppCoreBranchesRouteRouteChildren: AppCoreBranchesRouteRouteChildren = {
  AppCoreBranchesCreateRoute: AppCoreBranchesCreateRoute,
  AppCoreBranchesIndexRoute: AppCoreBranchesIndexRoute,
  AppCoreBranchesIdUpdateRoute: AppCoreBranchesIdUpdateRoute,
}

const AppCoreBranchesRouteRouteWithChildren =
  AppCoreBranchesRouteRoute._addFileChildren(AppCoreBranchesRouteRouteChildren)

interface AppCoreMembersRouteRouteChildren {
  AppCoreMembersCreateRoute: typeof AppCoreMembersCreateRoute
  AppCoreMembersIndexRoute: typeof AppCoreMembersIndexRoute
  AppCoreMembersIdUpdateRoute: typeof AppCoreMembersIdUpdateRoute
}

const AppCoreMembersRouteRouteChildren: AppCoreMembersRouteRouteChildren = {
  AppCoreMembersCreateRoute: AppCoreMembersCreateRoute,
  AppCoreMembersIndexRoute: AppCoreMembersIndexRoute,
  AppCoreMembersIdUpdateRoute: AppCoreMembersIdUpdateRoute,
}

const AppCoreMembersRouteRouteWithChildren =
  AppCoreMembersRouteRoute._addFileChildren(AppCoreMembersRouteRouteChildren)

interface AppCoreUsersRouteRouteChildren {
  AppCoreUsersCreateRoute: typeof AppCoreUsersCreateRoute
  AppCoreUsersIndexRoute: typeof AppCoreUsersIndexRoute
  AppCoreUsersIdUpdateRoute: typeof AppCoreUsersIdUpdateRoute
  AppCoreUsersTeamCreateRoute: typeof AppCoreUsersTeamCreateRoute
  AppCoreUsersTeamIndexRoute: typeof AppCoreUsersTeamIndexRoute
  AppCoreUsersTeamIdUpdateRoute: typeof AppCoreUsersTeamIdUpdateRoute
}

const AppCoreUsersRouteRouteChildren: AppCoreUsersRouteRouteChildren = {
  AppCoreUsersCreateRoute: AppCoreUsersCreateRoute,
  AppCoreUsersIndexRoute: AppCoreUsersIndexRoute,
  AppCoreUsersIdUpdateRoute: AppCoreUsersIdUpdateRoute,
  AppCoreUsersTeamCreateRoute: AppCoreUsersTeamCreateRoute,
  AppCoreUsersTeamIndexRoute: AppCoreUsersTeamIndexRoute,
  AppCoreUsersTeamIdUpdateRoute: AppCoreUsersTeamIdUpdateRoute,
}

const AppCoreUsersRouteRouteWithChildren =
  AppCoreUsersRouteRoute._addFileChildren(AppCoreUsersRouteRouteChildren)

interface AppCoreBillingPlansRouteRouteChildren {
  AppCoreBillingPlansCreateRoute: typeof AppCoreBillingPlansCreateRoute
  AppCoreBillingPlansIndexRoute: typeof AppCoreBillingPlansIndexRoute
  AppCoreBillingPlansPlanIdUpdateRoute: typeof AppCoreBillingPlansPlanIdUpdateRoute
}

const AppCoreBillingPlansRouteRouteChildren: AppCoreBillingPlansRouteRouteChildren =
  {
    AppCoreBillingPlansCreateRoute: AppCoreBillingPlansCreateRoute,
    AppCoreBillingPlansIndexRoute: AppCoreBillingPlansIndexRoute,
    AppCoreBillingPlansPlanIdUpdateRoute: AppCoreBillingPlansPlanIdUpdateRoute,
  }

const AppCoreBillingPlansRouteRouteWithChildren =
  AppCoreBillingPlansRouteRoute._addFileChildren(
    AppCoreBillingPlansRouteRouteChildren,
  )

interface AppCoreBillingSubscriptionsRouteRouteChildren {
  AppCoreBillingSubscriptionsIndexRoute: typeof AppCoreBillingSubscriptionsIndexRoute
}

const AppCoreBillingSubscriptionsRouteRouteChildren: AppCoreBillingSubscriptionsRouteRouteChildren =
  {
    AppCoreBillingSubscriptionsIndexRoute:
      AppCoreBillingSubscriptionsIndexRoute,
  }

const AppCoreBillingSubscriptionsRouteRouteWithChildren =
  AppCoreBillingSubscriptionsRouteRoute._addFileChildren(
    AppCoreBillingSubscriptionsRouteRouteChildren,
  )

interface AppCoreRouteRouteChildren {
  AppCoreBranchesRouteRoute: typeof AppCoreBranchesRouteRouteWithChildren
  AppCoreMembersRouteRoute: typeof AppCoreMembersRouteRouteWithChildren
  AppCoreUsersRouteRoute: typeof AppCoreUsersRouteRouteWithChildren
  AppCoreAnalyzeRoute: typeof AppCoreAnalyzeRoute
  AppCoreAssistantRoute: typeof AppCoreAssistantRoute
  AppCoreDashboardRoute: typeof AppCoreDashboardRoute
  AppCoreReportsRoute: typeof AppCoreReportsRoute
  AppCoreBillingPlansRouteRoute: typeof AppCoreBillingPlansRouteRouteWithChildren
  AppCoreBillingSubscriptionsRouteRoute: typeof AppCoreBillingSubscriptionsRouteRouteWithChildren
  AppCoreCheckInsScannerRoute: typeof AppCoreCheckInsScannerRoute
  AppCoreOrganizationCreateRoute: typeof AppCoreOrganizationCreateRoute
  AppCoreOrganizationProfileRoute: typeof AppCoreOrganizationProfileRoute
  AppCoreOrganizationIndexRoute: typeof AppCoreOrganizationIndexRoute
  AppCoreOrganizationIdUpdateRoute: typeof AppCoreOrganizationIdUpdateRoute
  AppCoreOrganizationModulesCreateRoute: typeof AppCoreOrganizationModulesCreateRoute
  AppCoreOrganizationModulesIndexRoute: typeof AppCoreOrganizationModulesIndexRoute
  AppCoreOrganizationModulesIdUpdateRoute: typeof AppCoreOrganizationModulesIdUpdateRoute
}

const AppCoreRouteRouteChildren: AppCoreRouteRouteChildren = {
  AppCoreBranchesRouteRoute: AppCoreBranchesRouteRouteWithChildren,
  AppCoreMembersRouteRoute: AppCoreMembersRouteRouteWithChildren,
  AppCoreUsersRouteRoute: AppCoreUsersRouteRouteWithChildren,
  AppCoreAnalyzeRoute: AppCoreAnalyzeRoute,
  AppCoreAssistantRoute: AppCoreAssistantRoute,
  AppCoreDashboardRoute: AppCoreDashboardRoute,
  AppCoreReportsRoute: AppCoreReportsRoute,
  AppCoreBillingPlansRouteRoute: AppCoreBillingPlansRouteRouteWithChildren,
  AppCoreBillingSubscriptionsRouteRoute:
    AppCoreBillingSubscriptionsRouteRouteWithChildren,
  AppCoreCheckInsScannerRoute: AppCoreCheckInsScannerRoute,
  AppCoreOrganizationCreateRoute: AppCoreOrganizationCreateRoute,
  AppCoreOrganizationProfileRoute: AppCoreOrganizationProfileRoute,
  AppCoreOrganizationIndexRoute: AppCoreOrganizationIndexRoute,
  AppCoreOrganizationIdUpdateRoute: AppCoreOrganizationIdUpdateRoute,
  AppCoreOrganizationModulesCreateRoute: AppCoreOrganizationModulesCreateRoute,
  AppCoreOrganizationModulesIndexRoute: AppCoreOrganizationModulesIndexRoute,
  AppCoreOrganizationModulesIdUpdateRoute:
    AppCoreOrganizationModulesIdUpdateRoute,
}

const AppCoreRouteRouteWithChildren = AppCoreRouteRoute._addFileChildren(
  AppCoreRouteRouteChildren,
)

interface AppRouteLazyRouteChildren {
  AppAuthRouteRoute: typeof AppAuthRouteRouteWithChildren
  AppCoreRouteRoute: typeof AppCoreRouteRouteWithChildren
}

const AppRouteLazyRouteChildren: AppRouteLazyRouteChildren = {
  AppAuthRouteRoute: AppAuthRouteRouteWithChildren,
  AppCoreRouteRoute: AppCoreRouteRouteWithChildren,
}

const AppRouteLazyRouteWithChildren = AppRouteLazyRoute._addFileChildren(
  AppRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteLazyRoute: AppRouteLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
